### ISSUE TITLE
Jython 2.7.0 incompatibility: 'module' object has no attribute 'create_default_context

### ISSUE THREAD

**Issue by wo1f1ow** [doyensec/inql#23]
When I load URL I get this output:
..
InQL Scanner Started! (tmpdir: /private/var/folders/n6/n3x71ldn5flc4z9lz79bgpqc0000gn/T/tmp7Jyc3e )
Quering GraphQL schema from: https://example.com
Proxy ENABLED: localhost:8080
Detect arguments is ENABLED, known types will be replaced with placeholder values
'module' object has no attribute 'create_default_context'
..

And error:
Exception in thread Thread-2:Traceback (most recent call last):
  File "/Users/user/Documents/jd-gui-osx-1.6.6/jython-standalone-2.7.0.jar/Lib/threading.py", line 222, in _Thread__bootstrap
    self.run()
  File "/Users/user/Documents/jd-gui-osx-1.6.6/jython-standalone-2.7.0.jar/Lib/threading.py", line 213, in run
    self._target(*self._args, **self._kwargs)
  File "/var/folders/n6/n3x71ldn5flc4z9lz79bgpqc0000gn/T/tmpveinaR/inql/utils.py", line 154, in async_run
  File "/var/folders/n6/n3x71ldn5flc4z9lz79bgpqc0000gn/T/tmpveinaR/inql/widgets/tab.py", line 296, in async_run
  File "/var/folders/n6/n3x71ldn5flc4z9lz79bgpqc0000gn/T/tmpveinaR/inql/introspection.py", line 277, in init
  File "/Users/user/Documents/jd-gui-osx-1.6.6/jython-standalone-2.7.0.jar/Lib/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Users/user/Documents/jd-gui-osx-1.6.6/jython-standalone-2.7.0.jar/Lib/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer, but got <type 'NoneType'>

Any ideas how I can fix this?

**Comment by thypon** [comment]
Have you tried with a known working endpoint?

`https://anilist.co/graphql` should do the trick.

**Comment by thypon** [comment]
Also knowing:

1. your install steps
2. your OS, java and jython version (and in case burp version)
3. Your command line for running what you run

Can be helpful.

**Comment by wo1f1ow** [comment]
> Have you tried with a known working endpoint?
> 
> `https://anilist.co/graphql` should do the trick.

Tried that endpoint and got the same error. More information as requested:
1. My installation steps:
Installed the app from Burp Extender App Store.
2. Python environment in options is set to: jython-standalone-2.7.0.jar. My OS is Catalina 10.15.5, java version "13.0.1" 2019-10-15, Java(TM) SE Runtime Environment (build 13.0.1+9), Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
3. Not running anything from command line. Using the Burp Extension.

The nQL Stand-Alone UI version works fine but I would like it to get it working in Burp for better workflow. Maybe I have the wrong jython version?

**Comment by thypon** [comment]
I tried with your setup and it seems to be related to jython 2.7.0 not having the create_default_context on ssl context creation.

They had similar issue in other projects too: 

https://github.com/rabbitmq/rabbitmq-management/issues/225

**Comment by thypon** [comment]
As a workaround you may use a more recent version of jython.

https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.2/jython-standalone-2.7.2.jar

**Comment by xyele** [comment]
I have the same issue, and I'm getting other errors with Jython 2.7.2

**Comment by thypon** [comment]
@thypon fixed in https://github.com/doyensec/inql/releases/tag/v3.0.0

**Comment by xyele** [comment]
I would like to use jython 2.7.2 but burp is messing with this version on my system ¯\_(ツ)_/¯. So I have to use 2.7.0 and im still getting same error with @wo1f1ow.

**Comment by thypon** [comment]
Ehi @xyele can you please open an issue with the new template format providing url, stacktrace, Java version, etc?

It may be possible that the error is at the same line, but the issue is arising from another reason.
